# Numpy notes by JedLueng 5 Feb 2021 


Source:https://www.codecademy.com/article/introduction-to-numpy-and-pandas

In [ ]:
NumPy = efficient numerical operations on large quantities of data. 

In [1]:
import numpy as np

In [2]:
#Make numpy array from list 
list1 = [1,2,3,4,5]
array1 = np.array(list1)
print(array1)

[1 2 3 4 5]


In [3]:
#Make two dimension arrage 
list2 = [[1,2,3], [4,5,6]]
array2 = np.array(list2)
print(array2)

[[1 2 3]
 [4 5 6]]


Operation on NumPy arrays
Selecting array elements

Slicing arrays

Reshaping arrays

Splitting arrays

Combining arrays

Numerical operations (min, max, mean, etc)


In [5]:
toyPrices = np.array([5,8,3,6])
print(toyPrices - 2) # Minus 2 in all numbers in numpy arrays 
#Faster than loop

[3 6 1 4]
