# Broadcasting 

TWo arrays have different 

In [4]:
#Comparision 

import numpy as np 

a = np.arange(1,10).reshape(3,3)
b = np.arange(1,4).reshape(3,1)
c = np.arange(1,4)


In [7]:
a > 3
#Are a more than 3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [6]:
#Show A 
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
#Slice Array 
a[:,1]>3

array([False,  True,  True])

In [11]:
a.min()
#Show the minimum in the array
#sum(), min(), max(), mean(),median() 
#mean(), median(), std()

1

In [12]:
a.min(axis=1)

array([1, 4, 7])

# ALL GAMES

In [50]:
file = open("all_games.csv")
#numpy_array = np.genfromtxt(file, delimiter=",", dtype = None, names = ['meta_score', 'user_review'])
arrays = [np.array(map(int, line.split())) for line in open('all_games.csv')]
game = np.genfromtxt('all_games.csv', delimiter=',', invalid_raise= False, usecols=[2,3],skip_header=1, max_rows=1000, missing_values=['tbd','Nintendo'])
game

array([[99. ,  9.1],
       [98. ,  7.4],
       [98. ,  7.7],
       ...,
       [87. ,  5.7],
       [87. ,  8.1],
       [87. ,  8.8]])

In [52]:
#Average and STD 
column_means = game.mean(axis=0)

array([nan, nan])

In [56]:
import pandas as pd
df = pd.read_csv ('all_games.csv')
print(df)

                                             name   platform  meta_score  \
0            The Legend of Zelda: Ocarina of Time   Nintendo          99   
1                        Tony Hawk's Pro Skater 2       Sony          98   
2                             Grand Theft Auto IV       Sony          98   
3                                     SoulCalibur       Sega          98   
4                             Grand Theft Auto IV  Microsoft          98   
...                                           ...        ...         ...   
18795                    Fast & Furious: Showdown  Microsoft          22   
18796                     Drake of the 99 Dragons  Microsoft          22   
18797  Afro Samurai 2: Revenge of Kuma Volume One       Sony          21   
18798   Infestation: Survivor Stories (The War Z)         PC          20   
18799         Leisure Suit Larry: Box Office Bust         PC          20   

      user_review  year  month  day  
0             9.1  1998     11   23  
1          

In [68]:
meta_score_df = df[['meta_score']]
user_review_df = df[['user_review']]


In [82]:
meta_score_df.std()

meta_score    12.225006
dtype: float64

In [81]:
meta_score_df.mean()

meta_score    70.648883
dtype: float64

In [89]:
meta_score_df[meta_score_df > 95].dropna()

meta_score
0         99.0
1         98.0
2         98.0
3         98.0
4         98.0
5         97.0
6         97.0
7         97.0
8         97.0
9         97.0
10        97.0
11        97.0
12        97.0
13        97.0
14        97.0
15        97.0
16        97.0
17        97.0
18        97.0
19        97.0
20        97.0
21        97.0
22        97.0
23        97.0
24        96.0
25        96.0
26        96.0
27        96.0
28        96.0
29        96.0
30        96.0
31        96.0
32        96.0
33        96.0
34        96.0
35        96.0
36        96.0
37        96.0
38        96.0
39        96.0
40        96.0
41        96.0
42        96.0
43        96.0
44        96.0