In [ ]:
import pandas as pd
import numpy as np


In [ ]:
df = pd.read_csv('titanic_train.csv')

In [ ]:
Y = df.Survived

In [ ]:
df.head(1)

In [ ]:
X = df.drop(columns=['PassengerId','Survived','Name', 'SibSp','Parch','Ticket','Cabin'])

In [ ]:
from sklearn.model_selection import train_test_split


In [ ]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3, random_state=1)

In [ ]:
X_train.Age.mean()

30.08266129032258

In [ ]:
X.Age.mean()

29.69911764705882

In [ ]:
X_test.Age.mean()

28.82646788990826

In [ ]:
X_train.head()

Pclass     Sex   Age     Fare Embarked
114       3  female  17.0  14.4583        C
874       2  female  28.0  24.0000        C
76        3    male   NaN   7.8958        S
876       3    male  20.0   9.8458        S
674       2    male   NaN   0.0000        S

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.compose import ColumnTransformer

In [ ]:
imp1 = SimpleImputer(strategy = 'mean')
imp2 = SimpleImputer(strategy = 'most_frequent')

In [ ]:
tf = ColumnTransformer([('impage',imp1,[2]),('impemb',imp2,[4])], remainder='passthrough')

In [ ]:
#X_train = tf.fit_transform(X_train)

In [ ]:
X_train[0]

array([17.0, 'C', 3, 'female', 14.4583], dtype=object)

In [ ]:
enc = OneHotEncoder()

In [ ]:
tf1 = ColumnTransformer([('OneHot', enc, [1, 3])],remainder='passthrough')
#X_train = tf1.fit_transform(X_train)

In [ ]:
X_train[0]

array([1.0, 0.0, 0.0, 1.0, 0.0, 17.0, 3, 14.4583], dtype=object)

In [ ]:
scl = MinMaxScaler()
tf2 = ColumnTransformer([('MinMax', scl, [5, 7])],remainder='passthrough')
#X_train = tf2.fit_transform(X_train)

In [ ]:
X_train[0]

In [ ]:
pca = PCA(n_components=5)
#pca.fit_transform(X_train)

In [ ]:
pca.explained_variance_ratio_

array([4.67448688e-01, 2.73230845e-01, 1.81477147e-01, 5.93764358e-02,
       1.52409245e-02, 3.22596000e-03, 1.49512831e-32, 6.65562512e-33])

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(max_depth=4, max_features='auto')

In [ ]:
from sklearn.pipeline import Pipeline
pipe = Pipeline([('imputer', tf),
                 ('encoder', tf1),
                 ('scaler', tf2),
                 ('PCA', pca),
                 ('DecisionTree', dt)])

In [ ]:
pipe.fit(X_train, Y_train)
pipe.score(X_test, Y_test)

0.7686567164179104